### ISSUE TITLE
Issue while playing on Mobile

### ISSUE THREAD

**Issue by jarveycooper** [yuvrajb/Advanced-TicTacToe#1]
it works while playing on 3x3 grid; however after finishing this grid i'm unable to tap on the continue icon (double right arrow). also nothing happens while tapping on the reload icon. 

did you make it mobile compatible?

**Comment by yuvrajb** [comment]
hi jarvey, thanks for raising an issue.
i checked on several mobiles and it works for me!  however i'll have a more look around and keep you posted.
